// Generated by Framer (3406f4c)
import {
    addPropertyControls as e,
    ControlType as l,
    lazy as t,
    QueryCache as r,
    QueryEngine as m
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as o
} from "./UDqms5IH3-0.js";
import {
    getRichTextJsonResolver as i
} from "./UDqms5IH3-1.js";
let n = t(() =>
        import ("https://framerusercontent.com/modules/pVk4QsoHxASnVtUBp6jr/ttReBBOK4JjO79S16uu9/CodeBlock.js")),
    c = {
        b0X3ZpNOv: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        HGqloDVxz: {
            isNullable: !0,
            type: l.String
        },
        hMRLbcgDu: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        j30veN8rM: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        P4iE9S3DH: {
            isNullable: !0,
            type: l.String
        },
        pIRBG_N_t: {
            isNullable: !0,
            type: l.Date
        },
        Pk9qkXX16: {
            isNullable: !0,
            type: l.RichText
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        }
    },
    s = ["id"],
    u = {
        type: 1
    },
    f = ["previousItemId"],
    d = ["nextItemId"],
    p = ["id", "P4iE9S3DH"],
    h = ["P4iE9S3DH", "id"],
    D = ["pIRBG_N_t"],
    S = {
        type: 0
    },
    N = ["b0X3ZpNOv"],
    I = ["P4iE9S3DH"],
    U = ["j30veN8rM"],
    w = ["hMRLbcgDu"],
    g = ["Pk9qkXX16"],
    y = ["HGqloDVxz"],
    H = [],
    x = e => {
        let l = H[e];
        if (l) return l().then(e => e.default);
    },
    R = {
        "module:pVk4QsoHxASnVtUBp6jr/ttReBBOK4JjO79S16uu9/CodeBlock.js:default": n
    },
    q = i(R),
    L = new m,
    P = new r(L),
    X = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./UDqms5IH3-chunk-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")],
                indexes: [new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 285,
                        to: 425
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 425,
                        to: 565
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 565,
                        to: 654
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 654,
                        to: 870
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 870,
                        to: 962
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 962,
                        to: 1388
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 1388,
                        to: 2997
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2997,
                        to: 25886
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 25886,
                        to: 25963
                    },
                    url: new URL("./UDqms5IH3-indexes-default-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: q,
                resolveVectorSetItem: x,
                schema: c
            }),
            ESXDN4fYP: new a({
                chunks: [new URL("./UDqms5IH3-chunk-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")],
                indexes: [new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 285,
                        to: 425
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: u,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 425,
                        to: 565
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 565,
                        to: 654
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 654,
                        to: 870
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 870,
                        to: 962
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 962,
                        to: 1388
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 1388,
                        to: 2997
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2997,
                        to: 25886
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 25886,
                        to: 25963
                    },
                    url: new URL("./UDqms5IH3-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/r3nCKeH2ptEZMd1BkWPm/o6Pghtn9S1voNR94oMUn/UDqms5IH3.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: q,
                resolveVectorSetItem: x,
                schema: c
            })
        },
        displayName: "Works"
    };
export default X;
e(X, {
    pIRBG_N_t: {
        title: "Date",
        type: l.Date
    },
    b0X3ZpNOv: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    P4iE9S3DH: {
        title: "Slug",
        type: l.String
    },
    j30veN8rM: {
        defaultValue: "",
        placeholder: "Blog Intro",
        title: "Intro",
        type: l.String
    },
    hMRLbcgDu: {
        title: "Image",
        type: l.ResponsiveImage
    },
    Pk9qkXX16: {
        defaultValue: "",
        title: "Content",
        type: l.RichText
    },
    HGqloDVxz: {
        defaultValue: "",
        displayTextArea: !0,
        maxLength: 155,
        title: "Meta Description",
        type: l.String
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/UDqms5IH3:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/UDqms5IH3:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await P.get({
            from: {
                data: X,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "P4iE9S3DH",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .P4iE9S3DH;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await P.get({
            from: {
                data: X,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "P4iE9S3DH",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerContractVersion": "1",
                "framerCollectionId": "UDqms5IH3",
                "framerSlug": "P4iE9S3DH",
                "framerColorSyntax": "false",
                "framerCollectionUtils": "1",
                "framerRecordIdKey": "id",
                "framerAutoSizeImages": "true",
                "framerEnumToDisplayNameUtils": "2",
                "framerData": ""
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}