// Generated by Framer (3406f4c)
export const props = {
    FXcWnj_0K: {
        borderRadius: 15,
        bottomLeftRadius: 15,
        bottomRightRadius: 15,
        darkTheme: "framerDark",
        font: {
            fontFamily: '"Fragment Mono", monospace',
            fontSize: "14px",
            fontStyle: "normal",
            fontWeight: 400,
            letterSpacing: "0em",
            lineHeight: "1.5em"
        },
        isMixedBorderRadius: false,
        lightTheme: "framerLight",
        padding: 30,
        paddingBottom: 30,
        paddingLeft: 30,
        paddingPerSide: false,
        paddingRight: 30,
        paddingTop: 30,
        theme: "framerDark",
        themeMode: "Static",
        topLeftRadius: 15,
        topRightRadius: 15
    }
};
export const fonts = {
    FXcWnj_0K: [{
        explicitInter: true,
        fonts: [{
            family: "Fragment Mono",
            source: "google",
            style: "normal",
            url: "https://fonts.gstatic.com/s/fragmentmono/v6/4iCr6K5wfMRRjxp0DA6-2CLnN4FNh4UI_1U.woff2",
            weight: "400"
        }]
    }]
};
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "props": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}