// Generated by Framer (3406f4c)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-ealXe .framer-styles-preset-kjddje {  }"];
export const className = "framer-ealXe";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}