// Generated by Framer (4c3178a)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    Container,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Footer from "#framer/local/canvasComponent/ATSeQid24/ATSeQid24.js";
import TopNavigation from "#framer/local/canvasComponent/hMHsvrLCH/hMHsvrLCH.js";
const TopNavigationFonts = getFonts(TopNavigation);
const ContainerWithFX = withFX(Container);
const FooterFonts = getFonts(Footer);
const breakpoints = {
    aLYk8NQQ1: "(min-width: 810px) and (max-width: 1199px)",
    pOcD7rxvj: "(max-width: 809px)",
    udqtGGdtG: "(min-width: 1200px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-i3q3q";
const variantClassNames = {
    aLYk8NQQ1: "framer-v-1djur1y",
    pOcD7rxvj: "framer-v-jn9otr",
    udqtGGdtG: "framer-v-fzgrm4"
};
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .5,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -60
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const breakpointRules = {
    aLYk8NQQ1: [".framer-i3q3q .framer-6fi5h-container { left: 0px; right: 0px; width: unset; }"],
    pOcD7rxvj: [".framer-i3q3q .framer-6fi5h-container { left: 0px; right: 0px; width: unset; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    aLYk8NQQ1: ".framer-1djur1y-override",
    pOcD7rxvj: ".framer-jn9otr-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-i3q3q.framer-qgfltm, .framer-i3q3q .framer-qgfltm { display: block; }", ".framer-i3q3q.framer-fzgrm4 { align-content: center; align-items: center; background-color: var(--token-f0aa30d0-ed2d-4ee4-8f5a-0a4b541f6ab8, #fafafa); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-i3q3q .framer-6fi5h-container { flex: none; height: auto; left: 50%; max-width: 840px; position: var(--framer-canvas-fixed-position, fixed); top: 0px; width: 840px; z-index: 9; }", ".framer-i3q3q .framer-yddg19 { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-i3q3q .framer-1iygehh-container { flex: none; height: auto; max-width: 840px; order: 1002; position: relative; width: 100%; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    aLYk8NQQ1: "(min-width: 810px) and (max-width: 1199px)",
    pOcD7rxvj: "(max-width: 809px)",
    udqtGGdtG: "(min-width: 1200px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "udqtGGdtG",
    Phone: "pOcD7rxvj",
    Tablet: "aLYk8NQQ1"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "udqtGGdtG"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "udqtGGdtG",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-f0aa30d0-ed2d-4ee4-8f5a-0a4b541f6ab8, rgb(250, 250, 250)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-fzgrm4", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                        aLYk8NQQ1: {
                            width: "min(100vw, 840px)"
                        },
                        pOcD7rxvj: {
                            width: "min(100vw, 840px)"
                        }
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 57,
                        width: "840px",
                        y: 0,
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                aLYk8NQQ1: {
                                    "data-framer-layout-hint-center-x": undefined,
                                    transformTemplate: undefined
                                },
                                pOcD7rxvj: {
                                    "data-framer-layout-hint-center-x": undefined,
                                    transformTemplate: undefined
                                }
                            },
                            children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                                __framer__animate: {
                                    transition: transition1
                                },
                                __framer__animateOnce: false,
                                __framer__scrollDirection: {
                                    direction: "down",
                                    target: animation
                                },
                                __framer__styleAppearEffectEnabled: true,
                                __framer__threshold: .5,
                                __perspectiveFX: false,
                                __targetOpacity: 1,
                                className: "framer-6fi5h-container",
                                "data-framer-layout-hint-center-x": true,
                                layoutScroll: true,
                                nodeId: "zRzhFXw4W",
                                rendersWithMotion: true,
                                scopeId: "kBnnZGLti",
                                transformTemplate: transformTemplate1,
                                children: /*#__PURE__*/ _jsx(TopNavigation, {
                                    height: "100%",
                                    id: "zRzhFXw4W",
                                    layoutId: "zRzhFXw4W",
                                    style: {
                                        maxWidth: "100%",
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-yddg19"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 66,
                    width: "min(100vw, 840px)",
                    y: 1e3,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-1iygehh-container",
                        nodeId: "iQm9Jrkp7",
                        scopeId: "kBnnZGLti",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                pOcD7rxvj: {
                                    variant: "qiP2N08Yh"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                height: "100%",
                                id: "iQm9Jrkp7",
                                layoutId: "iQm9Jrkp7",
                                style: {
                                    maxWidth: "100%",
                                    width: "100%"
                                },
                                variant: "avBGKSCl0",
                                width: "100%"
                            })
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1000
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"aLYk8NQQ1":{"layout":["fixed","fixed"]},"pOcD7rxvj":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"udqtGGdtG":[".framer-6fi5h-container",".framer-1iygehh-container"],"aLYk8NQQ1":[".framer-6fi5h-container",".framer-1iygehh-container"],"pOcD7rxvj":[".framer-6fi5h-container",".framer-1iygehh-container"]}
 * @framerBreakpoints {"udqtGGdtG":{"min":1200,"canvasClassName":"framer-fzgrm4-override","minHeight":1000,"name":"Desktop","width":1200,"rootFontSize":16},"aLYk8NQQ1":{"min":810,"max":1199,"canvasClassName":"framer-1djur1y-override","minHeight":1000,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"pOcD7rxvj":{"max":809,"canvasClassName":"framer-jn9otr-override","minHeight":1000,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant udqtGGdtG
 * @framerLayoutTemplate
 */
const FramerkBnnZGLti = withCSS(Component, css, "framer-i3q3q");
export default FramerkBnnZGLti;
FramerkBnnZGLti.displayName = "Default Template";
FramerkBnnZGLti.defaultProps = {
    height: 1e3,
    width: 1200
};
addFonts(FramerkBnnZGLti, [{
    explicitInter: true,
    fonts: []
}, ...TopNavigationFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerkBnnZGLti",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerDefaultVariant": "udqtGGdtG",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerLayoutTemplate": "",
                "framerBreakpoints": "{\"udqtGGdtG\":{\"min\":1200,\"canvasClassName\":\"framer-fzgrm4-override\",\"minHeight\":1000,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"aLYk8NQQ1\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-1djur1y-override\",\"minHeight\":1000,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"pOcD7rxvj\":{\"max\":809,\"canvasClassName\":\"framer-jn9otr-override\",\"minHeight\":1000,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"aLYk8NQQ1\":{\"layout\":[\"fixed\",\"fixed\"]},\"pOcD7rxvj\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerHitTargets": "{\"udqtGGdtG\":[\".framer-6fi5h-container\",\".framer-1iygehh-container\"],\"aLYk8NQQ1\":[\".framer-6fi5h-container\",\".framer-1iygehh-container\"],\"pOcD7rxvj\":[\".framer-6fi5h-container\",\".framer-1iygehh-container\"]}",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "1000",
                "framerIntrinsicWidth": "1200"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}