// Generated by Framer (3406f4c)
import siteMetadata from "https://framerusercontent.com/modules/13PHb84b7vfuGlrZ5HQQ/cy2oxpR3hzG3EWo73i5V/siteMetadata.js";
const valuesByLocaleId = {
    ESXDN4fYP: {
        v0: "瓜铺"
    }
};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1ymd0pm",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "oq76i6",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "1c77bq2",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-8rUYS",
        title: getLocalizedValue("v0", activeLocale) ? ? "About",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}