// Generated by Framer (2797bee)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-bpXcf .framer-styles-preset-18jbkou:not(.rich-text-wrapper), .framer-bpXcf .framer-styles-preset-18jbkou.rich-text-wrapper a { --framer-link-current-text-color: var(--token-ca491423-ed69-4073-9859-26d521a5ce20, #ff6b00); --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-ca491423-ed69-4073-9859-26d521a5ce20, #ff6b00); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-59e0057d-33bd-4745-b3ad-1acb6546c5ce, #333333); --framer-link-text-decoration: none; }"];
export const className = "framer-bpXcf";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}