// Generated by Framer (3406f4c)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as r,
    QueryEngine as t
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as m
} from "./MgdXj0Jdz-0.js";
import {
    getRichTextJsonResolver as o
} from "./MgdXj0Jdz-1.js";
let c = {
        aHGkSk25W: {
            isNullable: !0,
            type: l.String
        },
        cNJyz0FlC: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        e9kFrYHQD: {
            isNullable: !0,
            type: l.String
        },
        G73lBnwbP: {
            isNullable: !0,
            type: l.RichText
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        L9CRHt8pD: {
            isNullable: !0,
            type: l.String
        },
        mEgDPDobQ: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        xS0zLLmcF: {
            isNullable: !0,
            type: l.String
        },
        Z6Qkvc79m: {
            isNullable: !0,
            type: l.String
        }
    },
    i = ["id"],
    n = {
        type: 1
    },
    d = ["previousItemId"],
    s = ["nextItemId"],
    f = ["id", "e9kFrYHQD"],
    u = ["e9kFrYHQD", "id"],
    p = ["xS0zLLmcF"],
    g = {
        type: 0
    },
    h = ["e9kFrYHQD"],
    w = ["L9CRHt8pD"],
    S = ["mEgDPDobQ"],
    N = ["aHGkSk25W"],
    y = ["cNJyz0FlC"],
    X = ["G73lBnwbP"],
    L = ["Z6Qkvc79m"],
    x = [],
    R = e => {
        let l = x[e];
        if (l) return l().then(e => e.default);
    },
    z = {},
    D = o(z),
    j = new t,
    J = new r(j),
    M = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./MgdXj0Jdz-chunk-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")],
                indexes: [new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: i,
                    range: {
                        from: 0,
                        to: 73
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 73,
                        to: 145
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 145,
                        to: 213
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 213,
                        to: 326
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 326,
                        to: 439
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 439,
                        to: 525
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 525,
                        to: 604
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 604,
                        to: 674
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 674,
                        to: 790
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 790,
                        to: 906
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 906,
                        to: 2145
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: X,
                    range: {
                        from: 2145,
                        to: 8258
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 8258,
                        to: 8320
                    },
                    url: new URL("./MgdXj0Jdz-indexes-default-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: D,
                resolveVectorSetItem: R,
                schema: c
            }),
            ESXDN4fYP: new a({
                chunks: [new URL("./MgdXj0Jdz-chunk-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")],
                indexes: [new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: i,
                    range: {
                        from: 0,
                        to: 73
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 73,
                        to: 145
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 145,
                        to: 213
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 213,
                        to: 326
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: n,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 326,
                        to: 439
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 439,
                        to: 525
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 525,
                        to: 604
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 604,
                        to: 674
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 674,
                        to: 790
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 790,
                        to: 906
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 906,
                        to: 2145
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: X,
                    range: {
                        from: 2145,
                        to: 8258
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: g,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 8258,
                        to: 8320
                    },
                    url: new URL("./MgdXj0Jdz-indexes-ESXDN4fYP-0.framercms", "https://framerusercontent.com/modules/6Y2G2IOFxrpkqgnCInKs/UTBzH7lB41TsaoMkxLdn/MgdXj0Jdz.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: D,
                resolveVectorSetItem: R,
                schema: c
            })
        },
        displayName: "Thoughts"
    };
export default M;
e(M, {
    xS0zLLmcF: {
        defaultValue: "",
        placeholder: "Project Title",
        title: "Title",
        type: l.String
    },
    e9kFrYHQD: {
        title: "Slug",
        type: l.String
    },
    L9CRHt8pD: {
        defaultValue: "",
        placeholder: "2025",
        title: "Year",
        type: l.String
    },
    mEgDPDobQ: {
        defaultValue: "",
        placeholder: "Homepage Intro",
        title: "Homepage Intro",
        type: l.String
    },
    aHGkSk25W: {
        defaultValue: "",
        placeholder: "Workpage Intro",
        title: "Work Page Intro",
        type: l.String
    },
    cNJyz0FlC: {
        title: "Work Image",
        type: l.ResponsiveImage
    },
    G73lBnwbP: {
        defaultValue: "",
        title: "Content",
        type: l.RichText
    },
    Z6Qkvc79m: {
        defaultValue: "",
        displayTextArea: !0,
        maxLength: 155,
        title: "Meta Description",
        type: l.String
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/MgdXj0Jdz:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/MgdXj0Jdz:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [r] = await J.get({
            from: {
                data: M,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "e9kFrYHQD",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return r ? .e9kFrYHQD;
    },
    async getRecordIdBySlug(e, l) {
        let [r] = await J.get({
            from: {
                data: M,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "e9kFrYHQD",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return r ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerEnumToDisplayNameUtils": "2",
                "framerRecordIdKey": "id",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerColorSyntax": "false",
                "framerCollectionId": "MgdXj0Jdz",
                "framerSlug": "e9kFrYHQD",
                "framerData": "",
                "framerCollectionUtils": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}