// Generated by Framer (2797bee)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useComponentViewport,
    useLocaleCode,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/M6Hopw8T9emS1AxgFQxW/FPvQvHElH8FolQZW53ln/cI8El5bxi.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/jHk6Z8PFjqRcDgDWQOQc/KyGj4epSacLQVIbCHwju/LQ0giDQOM.js";
const enabledGestures = {
    pYQitzEFf: {
        hover: true
    }
};
const serializationHash = "framer-TgxKT";
const variantClassNames = {
    pYQitzEFf: "framer-v-162bklg"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const sharedDateFormatter = (value, formatOptions, locale) => {
    if (typeof value !== "string") return "";
    const date = new Date(value);
    if (isNaN(date.getTime())) return "";
    const fallbackLocale = "en-US";
    try {
        return date.toLocaleString(locale || fallbackLocale, formatOptions);
    } catch {
        return date.toLocaleString(fallbackLocale, formatOptions);
    }
};
const dateOptions = {
    month: "short",
    timeZone: "UTC",
    year: "numeric"
};
const toDateString = (value, activeLocale) => {
    return sharedDateFormatter(value, dateOptions, activeLocale);
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    date,
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        oK7sGTDNz: title ? ? props.oK7sGTDNz ? ? "How I built my Framer template empire",
        stPoIUtbS: link ? ? props.stPoIUtbS,
        Xp1T8htK1: date ? ? props.Xp1T8htK1 ? ? "2025-07-12T00:00:00.000Z"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Xp1T8htK1,
        oK7sGTDNz,
        stPoIUtbS,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "pYQitzEFf",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const activeLocaleCode = useLocaleCode();
    const textContent = toDateString(Xp1T8htK1, activeLocaleCode);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: stPoIUtbS,
                    motionChild: true,
                    nodeId: "pYQitzEFf",
                    openInNewTab: false,
                    scopeId: "jOI374W9s",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-162bklg",className,classNames)} framer-47kd21`,
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "pYQitzEFf",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "pYQitzEFf-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-t1dtgm",
                                    "data-styles-preset": "cI8El5bxi",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-dcda7a06-a063-4e13-bdb5-b6cc4a0e2211, rgb(117, 117, 117)))"
                                    },
                                    children: "Content"
                                })
                            }),
                            className: "framer-1writ1e",
                            "data-framer-name": "Date",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "SVU03_Lil",
                            style: {
                                "--extracted-r6o4lv": "var(--token-dcda7a06-a063-4e13-bdb5-b6cc4a0e2211, rgb(117, 117, 117))"
                            },
                            text: textContent,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-moh1hv",
                                    "data-styles-preset": "LQ0giDQOM",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3b0f98aa-c16a-4b12-80a4-e1056304b9fa, rgb(0, 0, 0)))"
                                    },
                                    children: "How I built my Framer template empire"
                                })
                            }),
                            className: "framer-j2fnji",
                            "data-framer-name": "Title",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "tlRk0sKwO",
                            style: {
                                "--extracted-r6o4lv": "var(--token-3b0f98aa-c16a-4b12-80a4-e1056304b9fa, rgb(0, 0, 0))"
                            },
                            text: oK7sGTDNz,
                            variants: {
                                "pYQitzEFf-hover": {
                                    "--extracted-r6o4lv": "var(--token-ca491423-ed69-4073-9859-26d521a5ce20, rgb(255, 107, 0))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                "pYQitzEFf-hover": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-moh1hv",
                                            "data-styles-preset": "LQ0giDQOM",
                                            style: {
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-ca491423-ed69-4073-9859-26d521a5ce20, rgb(255, 107, 0)))"
                                            },
                                            children: "How I built my Framer template empire"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-TgxKT.framer-47kd21, .framer-TgxKT .framer-47kd21 { display: block; }", ".framer-TgxKT.framer-162bklg { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 800px; }", ".framer-TgxKT .framer-1writ1e { flex: none; height: auto; min-width: 80px; position: relative; white-space: pre; width: auto; }", ".framer-TgxKT .framer-j2fnji { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 29
 * @framerIntrinsicWidth 800
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"rgdeqLzV1":{"layout":["fixed","auto"]}}}
 * @framerVariables {"Xp1T8htK1":"date","oK7sGTDNz":"title","stPoIUtbS":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerjOI374W9s = withCSS(Component, css, "framer-TgxKT");
export default FramerjOI374W9s;
FramerjOI374W9s.displayName = "Blog Title Component";
FramerjOI374W9s.defaultProps = {
    height: 29,
    width: 800
};
addPropertyControls(FramerjOI374W9s, {
    Xp1T8htK1: {
        defaultValue: "2025-07-12T00:00:00.000Z",
        title: "Date",
        type: ControlType.Date
    },
    oK7sGTDNz: {
        defaultValue: "How I built my Framer template empire",
        title: "Title",
        type: ControlType.String
    },
    stPoIUtbS: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerjOI374W9s, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerjOI374W9s",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"rgdeqLzV1\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "800",
                "framerVariables": "{\"Xp1T8htK1\":\"date\",\"oK7sGTDNz\":\"title\",\"stPoIUtbS\":\"link\"}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "29",
                "framerColorSyntax": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./jOI374W9s.map