// Generated by Framer (3406f4c)
const valuesByLocaleId = {};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        description: "肯定室",
        favicon: "https://framerusercontent.com/assets/cvIBjgWMRAsmuli8ifffbQulYY.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/l5Pje6cd021V2N4CycrYakrmmyA.png",
        title: "AFFIRMATORIUM"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}