// Generated by Framer (3406f4c)
const valuesByLocaleId = {
    ESXDN4fYP: {
        v0: ({
            b0X3ZpNOv
        }) => `${b0X3ZpNOv!==undefined?toString(b0X3ZpNOv):"{{b0X3ZpNOv}}"} - 肯定室`,
        v1: ({
            HGqloDVxz
        }) => `${HGqloDVxz!==undefined?toString(HGqloDVxz):"{{HGqloDVxz}}"}`
    }
};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
const toString = value => {
    return typeof value === "string" ? value : String(value);
};
export default function metadata(params, activeLocale) {
    const b0X3ZpNOv = params ? .["b0X3ZpNOv"];
    const HGqloDVxz = params ? .["HGqloDVxz"];
    return {
        breakpoints: [{
            hash: "q40itf",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "1pq8jc9",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "by3gvf",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: getLocalizedValue("v1", activeLocale) ? .({
            HGqloDVxz
        }) ? ? `${HGqloDVxz!==undefined?toString(HGqloDVxz):"{{HGqloDVxz}}"}`,
        elements: {},
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-EsTDz",
        title: getLocalizedValue("v0", activeLocale) ? .({
            b0X3ZpNOv
        }) ? ? `${b0X3ZpNOv!==undefined?toString(b0X3ZpNOv):"{{b0X3ZpNOv}}"} - AFFIRMATORIUM`,
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}